#!/bin/bash
#
# Configure Finch Port Forwarding for Public Access
#
# This script configures Lima VM to forward ports to all network interfaces (0.0.0.0)
# instead of just localhost (127.0.0.1).
#
# Usage: ./configure-finch-ports.sh [HTTP_PORT] [HTTPS_PORT]
# Example: ./configure-finch-ports.sh 8080 1443
#

set -e

# Default ports
HTTP_PORT=${1:-80}
HTTPS_PORT=${2:-443}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  Finch Port Forwarding Configuration                                       ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Check if running on macOS
if [[ "$(uname)" != "Darwin" ]]; then
    echo -e "${RED}Error: This script is only for macOS systems${NC}"
    exit 1
fi

# Check if Finch is installed
if ! command -v finch &> /dev/null; then
    echo -e "${RED}Error: Finch is not installed${NC}"
    echo "Install Finch: brew install --cask finch"
    exit 1
fi

# Get Finch config path
FINCH_CONFIG="$HOME/.finch/finch.yaml"

echo "Configuration file: $FINCH_CONFIG"
echo "HTTP Port: $HTTP_PORT (guest: 80)"
echo "HTTPS Port: $HTTPS_PORT (guest: 443)"
echo ""

# Backup existing config if it exists
if [[ -f "$FINCH_CONFIG" ]]; then
    BACKUP_FILE="${FINCH_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}Backing up existing configuration to: $BACKUP_FILE${NC}"
    cp "$FINCH_CONFIG" "$BACKUP_FILE"
fi

# Create .finch directory if it doesn't exist
mkdir -p "$HOME/.finch"

# Generate new configuration
cat > "$FINCH_CONFIG" << EOF
# Finch configuration file
# Generated by configure-finch-ports.sh on $(date)

# VM resources
cpus: 4
memory: 4GiB

# Port forwarding configuration
# Ports are forwarded to 0.0.0.0 (all interfaces) for public accessibility
portForwards:
  # Docker socket
  - guestSocket: /var/run/docker.sock
    hostSocket: /Users/{{.User}}/.finch/finch.sock
  
  # HTTP port
  - guestPort: 80
    hostIP: "0.0.0.0"
    hostPort: $HTTP_PORT
  
  # HTTPS port
  - guestPort: 443
    hostIP: "0.0.0.0"
    hostPort: $HTTPS_PORT
EOF

echo -e "${GREEN}✓ Configuration file created successfully${NC}"
echo ""

# Check if Finch VM is running
VM_STATUS=$(finch vm status 2>&1 || echo "unknown")

if echo "$VM_STATUS" | grep -q "running"; then
    echo -e "${YELLOW}Finch VM is running. Restarting to apply configuration...${NC}"
    echo ""
    
    echo "Stopping Finch VM..."
    finch vm stop
    
    echo "Starting Finch VM (this may take up to 2 minutes)..."
    finch vm start
    
    echo -e "${GREEN}✓ Finch VM restarted successfully${NC}"
elif echo "$VM_STATUS" | grep -q "stopped"; then
    echo -e "${YELLOW}Finch VM is stopped. Starting VM...${NC}"
    finch vm start
    echo -e "${GREEN}✓ Finch VM started successfully${NC}"
else
    echo -e "${YELLOW}Finch VM not initialized. Initializing...${NC}"
    finch vm init
    echo -e "${GREEN}✓ Finch VM initialized successfully${NC}"
fi

echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  Configuration Complete                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Port forwarding is now configured:"
echo "  • HTTP:  0.0.0.0:$HTTP_PORT → VM:80"
echo "  • HTTPS: 0.0.0.0:$HTTPS_PORT → VM:443"
echo ""
echo "Your application will be accessible from external machines at:"
echo "  • http://$(hostname):$HTTP_PORT"
echo "  • https://$(hostname):$HTTPS_PORT"
echo ""
echo -e "${GREEN}You can now deploy your application!${NC}"
echo ""
